import json
from typing import List, Dict, Any
from app.schemas.actions import BrowserAction, ActionType

class CodeSynthesizer:
    def __init__(self, scenario_title: str, base_url: str):
        self.scenario_title = scenario_title
        self.base_url = base_url
        self.recorded_actions: List[Dict[str, Any]] = []

    def record_step(self, action: BrowserAction, resolved_selector: str, reasoning: str):
        self.recorded_actions.append({
            "action": action,
            "selector": resolved_selector,
            "reasoning": reasoning
        })

    def generate_python(self) -> str:
        code_lines = [
            "# Generated by AutoQA - Autonomous Browser Testing Agent",
            "# Execution target: pytest-playwright",
            "import pytest",
            "from playwright.sync_api import Page, expect",
            "",
            f"def test_{self._sanitize_title(self.scenario_title)}(page: Page):",
            f'    """Test scenario: {self.scenario_title}"""',
            "    page.set_default_timeout(15000)",
            ""
        ]

        for item in self.recorded_actions:
            act: BrowserAction = item["action"]
            selector = item["selector"]
            thought = item["reasoning"]

            if thought:
                code_lines.append(f"    # {thought}")

            safe_sel = repr(selector) if selector else '""'

            if act.action_type == ActionType.NAVIGATE:
                code_lines.append(f'    page.goto("{act.url}")')
                code_lines.append('    page.wait_for_load_state("domcontentloaded")')
            elif act.action_type == ActionType.CLICK:
                code_lines.append(f'    page.locator({safe_sel}).click()')
            elif act.action_type == ActionType.FILL:
                safe_text = (act.text or "").replace('"', '\\"')
                code_lines.append(f'    page.locator({safe_sel}).fill("{safe_text}")')
            elif act.action_type == ActionType.HOVER:
                code_lines.append(f'    page.locator({safe_sel}).hover()')
            elif act.action_type == ActionType.KEY_PRESS:
                code_lines.append(f'    page.keyboard.press("{act.text}")')
            elif act.action_type == ActionType.SCROLL:
                if act.direction == "down":
                    code_lines.append(f'    page.mouse.wheel(0, {act.amount or 500})')
                elif act.direction == "up":
                    code_lines.append(f'    page.mouse.wheel(0, -{act.amount or 500})')
            elif act.action_type == ActionType.ASSERT_VISIBLE:
                assert_text = (act.assertion_text or "").replace('"', '\\"')
                code_lines.append(f'    expect(page.get_by_text("{assert_text}", exact=False)).to_be_visible()')
            elif act.action_type == ActionType.WAIT:
                code_lines.append('    page.wait_for_timeout(2000)')

            code_lines.append("")

        return "\n".join(code_lines)

    def generate_typescript(self) -> str:
        code_lines = [
            "// Generated by AutoQA - Autonomous Browser Testing Agent",
            "import { test, expect } from '@playwright/test';",
            "",
            f"test('{self.scenario_title}', async ({{ page }}) => {{",
            "  page.setDefaultTimeout(15000);",
            ""
        ]

        for item in self.recorded_actions:
            act: BrowserAction = item["action"]
            selector = item["selector"]
            thought = item["reasoning"]

            if thought:
                code_lines.append(f"  // {thought}")

            safe_sel = json.dumps(selector) if selector else '""'

            if act.action_type == ActionType.NAVIGATE:
                code_lines.append(f"  await page.goto('{act.url}');")
                code_lines.append("  await page.waitForLoadState('domcontentloaded');")
            elif act.action_type == ActionType.CLICK:
                code_lines.append(f"  await page.locator({safe_sel}).click();")
            elif act.action_type == ActionType.FILL:
                safe_text = (act.text or "").replace("'", "\\'")
                code_lines.append(f"  await page.locator({safe_sel}).fill('{safe_text}');")
            elif act.action_type == ActionType.HOVER:
                code_lines.append(f"  await page.locator({safe_sel}).hover();")
            elif act.action_type == ActionType.KEY_PRESS:
                code_lines.append(f"  await page.keyboard.press('{act.text}');")
            elif act.action_type == ActionType.SCROLL:
                delta = act.amount or 500
                if act.direction == "up":
                    delta = -delta
                code_lines.append(f"  await page.mouse.wheel(0, {delta});")
            elif act.action_type == ActionType.ASSERT_VISIBLE:
                assert_text = (act.assertion_text or "").replace("'", "\\'")
                code_lines.append(f"  await expect(page.getByText('{assert_text}', {{ exact: false }})).toBeVisible();")
            elif act.action_type == ActionType.WAIT:
                code_lines.append("  await page.waitForTimeout(2000);")

            code_lines.append("")

        code_lines.append("});")
        return "\n".join(code_lines)

    def _sanitize_title(self, title: str) -> str:
        clean = "".join([c if c.isalnum() else "_" for c in title.lower()])
        return "_".join(filter(None, clean.split("_")))
